davinci:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    p4_hand_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
          - p4_hand_roll
          - p4_hand_pitch
          - p4_instrument_slide
          - p4_instrument_roll
          - p4_instrument_pitch
          - p4_instrument_jaw_left
          - p4_instrument_jaw_right
        gains:
          p4_hand_roll: {p: 20, i: 0, d: 0, i_clamp: 100}
          p4_hand_pitch: {p: 50, i: 0, d: 0, i_clamp: 100}
          p4_instrument_slide: {p: -100, i: 0, d: 0, i_clamp: 100}
          p4_instrument_roll: {p: -5, i: 0, d: 0, i_clamp: 100}
          p4_instrument_pitch: {p: -5, i: 0, d: 0, i_clamp: 100}
          p4_instrument_jaw_left: {p: -5, i: 0, d: 0, i_clamp: 100}
          p4_instrument_jaw_right: {p: 5, i: 0, d: 0, i_clamp: 100}

    p4_instrument_slide_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_slide
        pid:
            p: -100
            i: -20
            d: 0
            i_clamp: 200

    p4_instrument_roll_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_roll
        pid:
            p: -8
            i: -2
            d: 0
            i_clamp: 100

    p4_instrument_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_pitch
        pid:
            p: -6
            i: 0
            d: 0
            i_clamp: 100

    p4_instrument_jaw_left_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_jaw_left
        pid:
            p: -6
            i: 0
            d: 0
            i_clamp: 100

    p4_instrument_jaw_right_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_jaw_right
        pid:
            p: 6
            i: 0
            d: 0
            i_clamp: 100
