davinci:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    p4_hand_roll_controller:
        type: effort_controllers/JointPositionController
        joint: p4_hand_roll
        pid:
            p: 1
            i: 1
            d: 1

    p4_hand_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: p4_hand_pitch
        pid:
            p: 1
            i: 1
            d: 1

    p4_instrument_slide_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_roll
        pid:
            p: 1
            i: 1
            d: 1

    p4_instrument_roll_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_roll
        pid:
            p: 1
            i: 1
            d: 1

    p4_instrument_pitch_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_pitch
        pid:
            p: 1
            i: 1
            d: 1

    p4_instrument_jaw_left_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_roll
        pid:
            p: 1
            i: 1
            d: 1

    p4_instrument_jaw_right_controller:
        type: effort_controllers/JointPositionController
        joint: p4_instrument_pitch
        pid:
            p: 1
            i: 1
            d: 1
