davinci:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

#    p4_hand_controller:
#        type: position_controllers/JointTrajectoryController
#        joints:
#          - p4_hand_roll
#          - p4_hand_pitch
#          - p4_instrument_slide
#          - p4_instrument_roll
#          - p4_instrument_pitch
#          - p4_instrument_jaw_right 

 # Position Controllers ---------------------------------------

    slide_position_controller:
        type: position_controllers/JointPositionController
        joint: p4_instrument_slide
        publish_rate: 100
        pid: {p: 100.0, i: 0.01, d: 10.0}
    hand_pitch_position_controller:
        type: position_controllers/JointPositionController
        joint: p4_hand_pitch
        publish_rate: 100
        pid: {p: 100.0, i: 0.01, d: 10.0}
    hand_roll_position_controller:
        type: position_controllers/JointPositionController
        joint: p4_hand_roll
        publish_rate: 100
        pid: {p: 100.0, i: 0.01, d: 10.0}
